name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mytcp:latest .

      - name: Login to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_IP }}" >> ~/.ssh/known_hosts

      - name: Push Docker image to EC2
        run: |
          docker save mytcp:latest | bzip2 | ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_IP }} 'bunzip2 | docker load'

      - name: Run Docker container on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_IP }} 'docker stop mytcp || true && docker rm mytcp || true'
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_IP }} 'docker run -d -p 9090:9090 --name mytcp mytcp:latest'
